FROM qnib/alpn-jre8
ADD clj-kstream-elasticsearch-sink.jar /usr/share/clj-kstream/clj-kstream-elasticsearch-sink.jar
ENTRYPOINT ["java", "-jar", "/usr/share/clj-kstream/clj-kstream-elasticsearch-sink.jar"]
CMD []